# -*- coding: utf-8 -*-
"""Gandhi_birthday.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Iy94VW48_kWR2UBirXL3y_gaXxAJSK9D
"""

import pandas as pd
name_and_codes={"Anushree":"katti",

    'Arpita': 'Eminems Rival',

    'Daksha':'Singing partner',

    'Sahil': 'O saathi song by Atif aslam',

    'Rachita':'baith kar baat karte hai',

    'Rahul' :'Black white and asian',

    'Saisha' : 'The one who is always high without smoking or drinking anything',

    'Sakshi': ''' "you're perfect re" ''',

    'Samuel':'Bike Craze/ Fame us Freaks',

    'Shreya':'listen to any song by Shreya Ghoshal',

    'Siddesh': 'GEC ke kadam kadam par mil jaaye' ,

    'Tanha':'John Cena',

    'Abijith': 'Bournvita- tayari jeet ki',

    'Ashutosh': 'gaadiwala aya',

    'Benito' : '69',

    'Bipasha':'"lets go waha oe"',

    'Deborah': 'test',

    'Earl' : '"easy re"',

    'Jordan' : 'opening batsman',

    'Krutika' : 'test',

    'Nidhi' : 'test',

    'Om' : "Resistor ka units",

    'Biju': 'The dictionary of swear words',

    'Umang': '"kya re tum"',

    'Vipul' :'IndiA'
    }
Gandhi_birthday=pd.Series(name_and_codes)



